### PR TITLE
Migrate from bcrypt-nodejs to bcrypt

### LINKED ISSUE #190: replace bcrypt-nodejs with bcrypt
**Specify project**
- server side issue

**Is your feature request related to a problem? Please describe.**
- In hackatalk project, npm bcrypt-nodejs is being used. [npm bcrypt-nodejs](https://www.npmjs.com/package/bcrypt-nodejs) says as following
```
bcrypt-nodejs is no longer actively maintained. Please use bcrypt or bcryptjs. See https://github.com/kelektiv/node.bcrypt.js/wiki/bcrypt-vs-brypt.js to learn more about these two options
```
So i suggest to replace bcrypt-nodejs with ~bcryptjs~ [bcrypt](https://github.com/kelektiv/node.bcrypt.js)

**Describe the solution you'd like**
write codes in below sequence, so make sure changes does not affect products.
1. write test codes for function `encryptCredential` and `validateCredential` in server/src/utils/auth.ts
2. replace bcrypt-nodejs with ~bcryptjs~ bcrypt

**Describe alternatives you've considered**
use alternative npm

### PR DESCRIPTION
**Pull request by 0916dhkim**
## Specify project
Server-side

## Description
Migrate `bcrypt-nodejs` package to `bcrypt` package.

## Related Issues
Resolve #190

## Tests
No test added.

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/hackatalk/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn lint && yarn tsc`
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by DevYuns** [comment]
Hi! thank you for your PR. 
If you finished this work, please request reviews to @hyochan or other reviewers so that they can check this PR. :)

**Comment by hyochan** [comment]
> Hi! thank you for your PR.
> If you finished this work, please request reviews to @hyochan or other reviewers so that they can check this PR. :)

Thanks for mentioning. However, this isn't necessary for the opensource since not many people know who the reviewers are when they are new to the projects.

**Comment by hyochan** [comment]
@DevYuns @ll0301 Could you review this wonderful `PR` and see if the updates work well in our scenario?

**Comment by DevYuns** [comment]
> @DevYuns @ll0301 Could you review this wonderful `PR` and see if the updates work well in our scenario? I found that merging this requires `database reset` since the user's credentials are all different from the `bcrypt-nodejs`.

Sure. I'll discuss about it with @ll0301

**Comment by ll0301** [comment]
I got this pr and tested it.
Screen Shot 2020-08-16 at 8 22 08 PM

The running environment is my Android phone and IOS simulator and expo web.
As a result, both sign up and sign in were successful in the three running environments.

*Sign up
Screenshot_20200816-202516_Expo
Screenshot_20200816-202658_Samsung Internet

1. Android 
Screenshot_20200816-204738_Expo
Screenshot_20200816-204748_Expo

2. IOS simulator
Screen Shot 2020-08-16 at 8 43 47 PM
Screen Shot 2020-08-16 at 8 44 10 PM

3. Expo Web
Screen Shot 2020-08-16 at 8 46 27 PM
Screen Shot 2020-08-16 at 8 33 26 PM

**Comment by hyochan** [comment]
> I got this pr and tested it.
> Screen Shot 2020-08-16 at 8 22 08 PM
> 
> The running environment is my Android phone and IOS simulator and expo web.
> As a result, both sign up and sign in were successful in the three running environments.
> 
> *Sign up
> Screenshot_20200816-202516_Expo
> Screenshot_20200816-202658_Samsung Internet
> 
> 1. Android
>    Screenshot_20200816-204738_Expo
>    Screenshot_20200816-204748_Expo
> 2. IOS simulator
> 
> Screen Shot 2020-08-16 at 8 43 47 PM
> 
> Screen Shot 2020-08-16 at 8 44 10 PM
> 
> 1. Expo Web
> 
> Screen Shot 2020-08-16 at 8 46 27 PM
> 
> Screen Shot 2020-08-16 at 8 33 26 PM
> 
> but,
> When I pressed the setting button in my Profile screen to log out of the mobile environment,
> the following error was found.
> 
> Screen Shot 2020-08-16 at 9 14 13 PM
> 
> IOS simulator
> Screen Shot 2020-08-16 at 8 34 18 PM
> 
> Android phone
> Screenshot_20200816-203430_Expo
> 
> choose dismiss and succeed in logging out.

Thanks for the specific testing. However, the issue you've provided that occurred with `FontAwesome`, I think this is solved by #203

**Pull request merged**
