### PR TITLE
Run relay-compiler Again

### PR DESCRIPTION
**Pull request by 0916dhkim**
## Specify project

Client-side

## Description

Updated GraphQL schema on server-side is not reflected on client-side.
I have run the following commands to regenerate source files.
```
yarn generate:local
yarn relay
```

## Tests

Snapshots should be updated in tests.

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/hackatalk/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn lint && yarn tsc`
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by 0916dhkim** [comment]
`yarn tsc` is failing, and I'm working on it.

**Comment by 0916dhkim** [comment]
@hyochan It seems like `photoURL` is a required field of `User`. Is it by design or can we make `photoURL` optional?

https://github.com/dooboolab/hackatalk/blob/6e87da8f3f59077f5d200fa210f9e8ea901c309c/server/prisma/schema.prisma#L22-L44

**Comment by hyochan** [comment]
> @hyochan It seems like `photoURL` is a required field of `User`. Is it by design or can we make `photoURL` optional?
> 
> https://github.com/dooboolab/hackatalk/blob/6e87da8f3f59077f5d200fa210f9e8ea901c309c/server/prisma/schema.prisma#L22-L44

Good point! `Prisma` always generates array to `required` fields, so we need to re-define this in `nexus` in https://github.com/dooboolab/hackatalk/blob/90b9184065ba8954f193ddab9630b63154ce3d1f/server/src/types/models/User.ts#L21.

However, I feel like this should be reverted to `String` instead of array currently. I've managed to make that in array to support scenarios like user's `gallery`. However, I feel like this should be separated into another table instead of `String` array.

I'll try to fix this on the server-side and when this is merged to master, I hope you do the following in this `PR`.

1. `git fetch upstream`. (You should have properly configured upstream branch)
2. `git rebase upstream/master` then resolve all conflicts.
     * You may ask for help on the next remote meetings if you find trouble.
3. `yarn schema` to get new `schema` from the `dev` server.
4. `yarn relay` to generate relay types.

I'll tell you when you can start working on it 🙌

**Comment by hyochan** [comment]
@0916dhkim You can continue working on it since #205 has been applied to our server, https://hackatalk.azurewebsites.net.

**Comment by 0916dhkim** [comment]
@hyochan I re-ran Relay on client-side, and there was no error from `tsc`. Please review the changes of generated files.

**Pull request merged**
