### PR TITLE
[Server] add ChannelService

### PR DESCRIPTION
**Pull request by 00aney**
- add findExistingChannel

## Specify project
- Server

## Description
Added ChannelService to remove duplicate code

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/hackatalk/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn lint && yarn tsc`
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by 00aney** [comment]
Does anyone know how to rebuild the client side? I worked on only backend but I am not sure why it failed on client side.

**Comment by hyochan** [comment]
@00aney I've just restarted this! Please try to `rebase` this if this is still failing.

**Review by hyochan — APPROVED** [review]
LGTM!

**Comment by hyochan** [comment]
@all-contributors Please add @00aney for code.

**Pull request merged**
