### PR TITLE
Image Slider

### PR DESCRIPTION
**Pull request by JongtaekChoi**
## Specify project
`react-native` 

## Description

I added the ImageSlider screen and its test. 
It shows images of a message screen. 
Nov-14-2020 23-27-57

## Tests

I added the following tests:

A snapshot test of the ImageSlider screen. 

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/hackatalk/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn lint && yarn tsc`
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by 0916dhkim** [comment]
@JongtaekChoi This is amazing. I can't wait to see this merged.

**Comment by JongtaekChoi** [comment]
> Thanks for the wonderful work!! However, the CI is failing.
> Also, could you tell if the below UI is correct?
> image

I think that the default image should not cross the status bar area. So I've changed about this.

**Comment by JongtaekChoi** [comment]
The CI process failed the server test. I don't know why because I didn't change any codes below the server folder.

**Comment by hyochan** [comment]
> > Thanks for the wonderful work!! However, the CI is failing.
> > Also, could you tell if the below UI is correct?
> > image
> 
> I think that the default image should not cross the status bar area. So I've changed about this.

OK! Understood 👍

**Comment by hyochan** [comment]
> The CI process failed the server test. I don't know why because I didn't change any codes below the server folder.

It happens intermittently, don't worry about that (I think it happens because of the heavy work but we are using the free version). I'll try to rerun it.

**Pull request merged**
