### PR TITLE
Tests migration and subscription message fixes

### PR DESCRIPTION
**Pull request by 0916dhkim**
## Specify project
Both

### Overview
Fix glitches regarding Relay message subscription.

#### Fix `onMessage` Server-side Logic.
- Remove `channelId` parameter from `onMessage` subscription. It is easier to subscribe once & receive updates of all channels.
- Pubsub is filtered by two criteria (both should be true):
    - The message is sent to a channel of which the authenticated user is a member.
    - The message is not sent by the authenticated user oneself. (Users are not notified for their own messages)
- Add `useSubscription` hook to `MainStackNavigator`. (Remove `requestSubscription` from `Messages` screen)
    - Wrap `subscriptionConfig` with `useMemo` hook as recommended by the Relay team: [documentation](https://relay.dev/docs/api-reference/use-subscription/#usesubscription)

#### Add `Authorization` Key to `connectionParams` for Web Socket Connections.
- Make Relay add `Authorization` to `connectionParams` by modifying `src/relay/subscription`.
    - Mixing `Promise`, `SubscribeObservable`, and `RelayObservable` is not trivial. Everything should be wrapped inside `RelayObservable` in order to function properly.
    - Flow of Relay subscription:
        1. Get auth token from `AsyncStorage` (Promise).
        2. Create subscription client with the token.
        3. Define subscription request (`subscriptions-transport-ws` Observable).
        4. Wrap everything inside Relay Observable.
        5. Execute.
- Server context for subscription is handled differently than context for queries. `onConnect` function should return `connectionParams`, so that `createContext` can access `Authorization` key (there is no `Authorization` header for web sockets). The solution from https://github.com/apollographql/apollo-server/issues/1796 is applied here.

#### Fix Express Request & Response Type Extension
Express's `Request` & `Response` interface can be extended using [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html)
```ts
// environment.d.ts
import {i18n} from 'i18next';

declare global {
  namespace Express {
    interface Request extends i18n {
      appSecret: string;
      appSecretEtc: string;
    }
  }
}
```
Also, single middleware for loading all environment variables is added in `app.ts` file.
(There were multiple middlwares loading different environment variables in `root.ts` file)

#### Package Updates
- `@testing-library/react-native` to 8.0.0
    - There is an issue with Testing Library + Jest where `waitFor` and `async/await` cannot be used together. `waitFor` is implemented with `setInterval` which is mocked by fake timer. It results in infinite waiting.
    - Related Issue: https://github.com/callstack/react-native-testing-library/issues/506
    - Fixed in PR: https://github.com/callstack/react-native-testing-library/pull/568 (included in version 8).
- `@types/react-native` to 0.64.0
- Downgrade `react-test-renderer` to 16.11.0
    - `react-test-renderer` version 17 crashes when rendering `react-native-gesture-handler`.
    - `react-native-gesture-handler` is a dependency of `react-navigation`, so it cannot be removed.
    - Updating `react-test-renderer` to version 17 should be blocked until the issue is resolved.

#### Minor Refactors.
- Gather `updater` codes to `src/relay/updaters`.
- Use Relay fragments instead of types from `src/types/graphql`.
    - Types from `src/types/graphql` require all fields including unnecessary fields. Relay fragment allows specifying the fields which are actually required for a component.
    - Refactored components:
        - `ProfileModal`
        - `BlockedUser`
        - `MainFriend`
        - `MessageListItem`
        - `UserListItem`
- Fix `@ts-ignore` from some `FlatList` props.

## Related Issues
- This fix is for PR #364
- `subscriptions-transport-ws` will be discontinued as per its [README](https://github.com/apollographql/subscriptions-transport-ws). Migration to `graphql-ws` should be considered.
    > The subscriptions-transport-ws library is not being actively maintained. It is recommended that you use the graphql-ws library instead. For details read the GraphQL over WebSockets announcement.

## Tests
A lot of test related issues are fixed.
- `client/src/providers/index.tsx`
    - Remove `environment` export. It is easier to create mock environment per test case than using a centralized mock environment because of Relay's caching behavior. Cached query from one test case can affect other test cases.
    - Remove `AllProviders` export. `AllProviders` is a helper component for `createTestElement`, but it is not reused anywhere else. Also, it is better to put all test-purpose components under `test` directory.
- `client/test/setUpTest.js`
    - Clean up after each test case. Actually this is against Kent Dodds's advice, but `@testing-library/react-native` does not seem to clean up automatically.
    ```ts
    afterEach(cleanup);
    ```
    - Exit process if there is any unhandled promise.
    ```ts
    process.on('unhandledRejection', (err) => {
        fail(err);
    });
    ```
- `client/test/testUtils.tsx`
    - Remove `createTestProps` helper function.
        - All screen components are refactored to use navigation hooks instead of `navigation` and `route` props.
        - `useNavigation` or `useRoute` can be mocked per-test basis with better type-safety (`createTestProps` casts everything to `any`).
    - Add `createMockNavigation` helper function.
        - It creates a mock navigation to be used for mocking `useNavigation` hook. Navigation object has a lot of methods and it is tedious to mock everything. This function generates a fully mocked navigation object.

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/hackatalk/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn lint && yarn tsc`
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by 0916dhkim** [comment]
@hyochan Tests are fixed and this PR is ready to be merged.

**Review by hyochan — APPROVED** [review]
Overall, fantastic!

Please re-request after the minor updates talked online 🙏

**Comment by 0916dhkim** [comment]
@hyochan `ComponentWrapper` test issue and Express type issue are fixed now.

**Review by hyochan — APPROVED** [review]
You rocked 👊

**Pull request merged**
