### PR TITLE
Client Side Message Screen (Image Sender, input text display, responsive screen) Edits

### PR DESCRIPTION
**Pull request by shljessie**
## Specify project
_ As part of the Client Side of Hackatalk I am making edits on the Message Screen. I plan to work on three parts

**1) Image Sender**
: Display Screen when user sends a photo

**2) Input Text Display** 
: Currently there is a weird selected effect in the input text section. I plan on revising that.

Screen Shot 2020-08-31 at 3 48 19 PM

**3) Responsive Screen**  
: Currently, the message sender section doesn't fit the screen perfectly well. I plan on revising that 
Screen Shot 2020-08-31 at 3 44 15 PM

 _

## Description

_ This is a PR for the Message Screen of Hackatalk. 

**1) Image Sender**
updates: Currently I have fixed the photosender. I plan on working on adjusting the width and height of the photo depending on its size of the photo the user sends 
&&  print image on flatlist that changes view depending on number of images set

**2) Input Text Sender** 
updates : no progress

**3) Responsive Screen**
updates : no progress
_

## Related Issues

_nothing yet_

## Tests

I added the following tests:

_Replace this with a list of the tests that you added as part of this PR. A change in behavior with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage](https://codecov.io/gh/dooboolab/hackatalk)._

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/hackatalk/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn lint && yarn tsc`
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by shljessie** [comment]
This is the circleci client error that I am currently getting. 
Screen Shot 2020-08-31 at 6 04 40 PM

According to the graphql schema, there is a image Urls in Message type that you showed me yesterday. 
Screen Shot 2020-08-31 at 6 04 06 PM

When I look into MessageProps, it looks likethis.
Screen Shot 2020-08-31 at 6 05 47 PM

I am confused of what data type I should be using to receive the imageurl @hyochan

**Comment by hyochan** [comment]
> This is the circleci client error that I am currently getting.
> Screen Shot 2020-08-31 at 6 04 06 PM
> 
> According to the graphql schema, there is a image Urls in Message type that you showed me yesterday.
> Screen Shot 2020-08-31 at 6 04 40 PM
> 
> When I look into MessageProps, it looks likethis.
> Screen Shot 2020-08-31 at 6 05 47 PM
> 
> I am confused of what data type I should be using to receive the imageurl @hyochan

Could you run `yarn generate && yarn relay` and try again?
Also try to rebase this!

**Review by hyochan — CHANGES_REQUESTED** [review]
Please re-request review!

**Comment by shljessie** [comment]
### **These are the changes I plan on making to Hackatalk today**
image
**1) onClick-> add missing change theme effect

2) change color of loading icon on light theme mode : currently the sending button loading icon disappears like the image below
image

3) add new menu button

4) change emoji icon placement to right side

5) get rid of or expand the size of the onselect outline effect

6) potential menu bar to see members in chatroom**

**Comment by shljessie** [comment]
Changed the text input bar icons. Made the input bar responsive


CqIU5JXFdy

Also limited the max width of messages.
**Before**
Screen Shot 2020-09-01 at 10 55 40 AM

**After**
Screen Shot 2020-09-01 at 6 48 59 PM

**Comment by shljessie** [comment]
@hyochan  sync!

**Pull request closed without merging**
