### PR TITLE
Add diagram

### PR DESCRIPTION
**Pull request by daadaadaah**
## Specify project
server

## Description
- Add a diagram that can easily understand the overall structure.

## Related Issues
x

## Tests
x

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/hackatalk/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [ ] Run `yarn lint && yarn tsc`
- [ ] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by daadaadaah** [comment]
I drew a diagram that can easily understand the overall structure. Hope this diagram helps other contributors.
If this diagram helps, I'd like to add it to the hackathon website too, what do you think? 
If it is added, it will be added to this part. 

스크린샷 2020-10-15 오후 4 38 19

**Comment by hyochan** [comment]
> I drew a diagram that can easily understand the overall structure. Hope this diagram helps other contributors.
> If this diagram helps, I'd like to add it to the [hackatalk-website](https://website.hackatalk.dev/docs/server/specification) too, what do you think?
> If it is added, it will be added to this part.
> 
> 스크린샷 2020-10-15 오후 4 38 19

It would be great to have it there too! Thanks for the contribution.

**Review by hyochan — APPROVED** [review]

**Comment by daadaadaah** [comment]
@hyochan 
I modified the diagram to correct the typo in the diagram. 😅

**Review by hyochan — CHANGES_REQUESTED** [review]
Please rebase correctly. U are changing lots of files that are not in your purpose.

**Review by hyochan — APPROVED** [review]
LGTM!

**Pull request merged**
