### PR TITLE
Save and delete users push token for device

### PR DESCRIPTION
**Pull request by hyochan**
## Specify project
both

## Description

This feature will make users able to chat with push notifications.

When clients request `createMessage` mutation on the server, the server will create message and grab all the `pushTokens` in the channel except the user who creates a message.

## Tests

* Tested `createMessage` mutation.

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/hackatalk/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn lint && yarn tsc`
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by hyochan** [comment]
@0916dhkim Any news?

**Comment by 0916dhkim** [comment]
@hyochan Sorry there was a personal emergency. I can get back working on this issue since the situation is almost settled.

**Comment by hyochan** [comment]
> @hyochan Sorry there was a personal emergency. I can get back working on this issue since the situation is almost settled.

Actually, no worry. I've just resolved that in https://github.com/dooboolab/hackatalk/commit/8fbddbe5cb130a21513f95e7d347ef4b6ad580bf

**Comment by 0916dhkim** [comment]
@hyochan Yes, it seems like all tests are passing except snapshots now. I guess #216 is also okay?

**Comment by hyochan** [comment]
> @hyochan Yes, it seems like all tests are passing except snapshots now. I guess #216 is also okay?

Yes this is fine now 🙌

**Pull request merged**
