### PR TITLE
Keyboard Automatic Search while Input Implemented

### PR DESCRIPTION
**Pull request by shljessie**
## Specify project
Added a new feature that loads the searched username inputs as the user types.
Also made changes to english grammatical errors in user error messages.

Screen Shot 2020-08-13 at 6 39 36 PM

## Description

Used the filter() function to pass on data that is filtered by search. 

## Related Issues

Wondering and Planning on implementing ways to enhance this by using Debounce or Throttle in case event overload occurs.

## Tests

I added the following tests:

_Replace this with a list of the tests that you added as part of this PR. A change in behavior with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage](https://codecov.io/gh/dooboolab/hackatalk)._

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ x] I read the [Contributor Guide](https://github.com/dooboolab/hackatalk/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x ] I signed the [CLA].
- [x ] Run `yarn lint && yarn tsc`
- [x ] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x ] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by LiteHell** [comment]
It's not important but your markdown is a bit broken in pr.

**Comment by hyochan** [comment]
@shljessie CLA!

**Comment by hyochan** [comment]
Please sign in for `CLA` @shljessie

**Comment by shljessie** [comment]
I've signed the CLA!

**Comment by 0916dhkim** [comment]
It looks awesome. Great work!

**Comment by shljessie** [comment]
> It looks awesome. Great work!

Thanks :)

**Comment by hyochan** [comment]
@all-contributors please add @shljessie for code.

**Pull request merged**
