### PR TITLE
Correct client's README and server in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by geoseong**
### "client" project
Update "Structures" section

### "server" project
- Fix mismatch between command line and description in `Setup environment`
- Change description in `Migration`
  ```
  Prisma lift will generate migration file for you.
  ```
  - The term "Prisma lift" cannot be found in Prisma Documentation, Youtube, or Google now.
  - "@prisma/lift" exists in npm but this redirects to "https://github.com/prisma/migrate" repository

## Tests

none. just changed documentation markdown

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/hackatalk/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [ ] Run `yarn lint && yarn tsc`
- [ ] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by geoseong** [comment]
@hyochan should I put `.ncurc.json`, `.prettierrc.js`, `.svgrrc` and `codecov.yml` into **Structures** in client's README? please let me know if this is not necessary to put this.

**Comment by hyochan** [comment]
> @hyochan should I put `.ncurc.json`, `.prettierrc.js`, `.svgrrc` and `codecov.yml` into **Structures** in client's README? please let me know if this is not necessary to put this.

I think it is already good enough!

**Comment by geoseong** [comment]
@hyochan in merged CONTRIBUTING.md, [this](https://github.com/dooboolab/hackatalk/blame/master/CONTRIBUTING.md#L74) should be replaced from `client` to `server` 😅.
```
1. Install your packages in `client` directory.
-> 1. Install your packages in `server` directory.
```

this is just a tiny thing to change so please change it directly.

**Comment by hyochan** [comment]
I'll update that. However, next time you can just give a `PR` on any minor fixes!

**Pull request merged**
