### PR TITLE
Fix logo touchable

### PR DESCRIPTION
**Pull request by rarira**
## Specify project
client related

## Description

[commit](https://github.com/dooboolab/hackatalk/commit/d0aae78c28d7bae12e4dbdb959b77cfe8eb40529) has fixed animation issue but Touchable onPress doesn't call because its child component has style `position: 'absolute'`.

So I make TouchableOpacity component also animated and give it `position: 'absolute'` style. Now AnimatedTouchableOpacity component deals with position(left and top) animation and AnimatedImage component deals with image size scaling animation.

## Related Issues

#437 

## Tests

I added the following tests:

nothing added

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x ] I read the [Contributor Guide](https://github.com/dooboolab/hackatalk/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [ x] I signed the [CLA].
- [x ] Run `yarn lint && yarn tsc`
- [x ] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [ x] I am willing to follow-up on review comments in a timely manner.

[wehack2021]-[Cloud]

### CODE REVIEW

**Comment by hyochan** [comment]
@DevYuns Looks like this `PR` is enhancement from your latest `PR`. Would you like to test this out?

**Comment by DevYuns** [comment]
@rarira Thank you for reporting. I just checked my PR, I find the reason that `Icon` does not touchable. This is because `zIndex`. So after removing a `zIndex` in  `logoAnimStyle`, It works. Could check this out?

**Comment by rarira** [comment]
> @rarira Thank you for reporting. I just checked my PR, I find the reason that `AnimatedImage` does not touchable. This is because `zIndex`. So after removing a `zIndex` in `logoAnimStyle`, It work as intended. Could you check this out?

I really doubt if we are on the same page(commit).
In my case, it doesn't work just without `zindex` ..

let me show you my screen.(I'm sorry that I don't know how to show touch point in ios simulator screen recording)
Red lines on the top of the screen is because of
```
        <TouchableOpacity
          testID="theme-test"
          onPress={(): void => changeThemeType()}
          style={{borderColor: 'red', borderWidth: 2}}>

```

If I touch that red line, it calls onPress.

Simulator Screen Recording - iPhone 12 Pro - 2021-07-29 at 12 02 01

**Comment by DevYuns** [comment]
@rarira oh.. this is my mistake. I try to remove `zIndex` in `logoAnimStlye` and add zIndex to `TouchbleOpacity` like below.
```
        <TouchableOpacity
          style={{zIndex: 20}}
          testID="theme-test"
          onPress={(): void => changeThemeType()}>
          <AnimatedImage
            style={[logoAnimStyle, {resizeMode: 'cover'}]}
            source={themeType === 'dark' ? IC_LOGO_D : IC_LOGO_W}
          />
        </TouchableOpacity>
```

It looks ok at first glance. but after adding a `borderColor` as you said, I realize that something wrong.

What about below code? I think we don't need a two animation Value. Make a `TouchableOpacity` animatable again,
then add `width` and `height` to `Image` for web support. It works for me.
```
        <AnimatedTouchableOpacity
          testID="theme-test"
          style={logoAnimStyle}
          onPress={(): void => changeThemeType()}>
          <Image
            style={{width: '100%', height: '100%', resizeMode: 'cover'}}
            source={themeType === 'dark' ? IC_LOGO_D : IC_LOGO_W}
          />
        </AnimatedTouchableOpacity>
```

**Comment by rarira** [comment]
> @rarira oh.. this is my mistake. I try to remove `zIndex` in `logoAnimStlye` and add zIndex to `TouchbleOpacity` like below.
> 
> ```
>         <TouchableOpacity
>           style={{zIndex: 20}}
>           testID="theme-test"
>           onPress={(): void => changeThemeType()}>
>           <AnimatedImage
>             style={[logoAnimStyle, {resizeMode: 'cover'}]}
>             source={themeType === 'dark' ? IC_LOGO_D : IC_LOGO_W}
>           />
>         </TouchableOpacity>
> ```
> 
> It looks ok at first glance. but after adding a `borderColor` as you said, I realize that something wrong.
> 
> What about below code? I think we don't need a two animation Value. Make a `TouchableOpacity` animatable again,
> then add `width` and `height` to `Image` for web support. It works for me.
> 
> ```
>         <AnimatedTouchableOpacity
>           testID="theme-test"
>           style={logoAnimStyle}
>           onPress={(): void => changeThemeType()}>
>           <Image
>             style={{width: '100%', height: '100%', resizeMode: 'cover'}}
>             source={themeType === 'dark' ? IC_LOGO_D : IC_LOGO_W}
>           />
>         </AnimatedTouchableOpacity>
> ```

It should work but I think that scaling logo image is needed, original version(which is on the appstore) had it. So I had to use two animated component.

**Comment by rarira** [comment]
> {width: '100%', height: '100%', resizeMode: 'cover'}

It's my mistake this time, we don't need two animStyle.
Thanks for your review

**Comment by DevYuns** [comment]
I think we are ready to request your review @hyochan !

**Review by hyochan — APPROVED** [review]
LGTM!

**Comment by hyochan** [comment]
@all-contributors Please add @rarira for code

**Pull request merged**
